### ISSUE TITLE
Workaround faulty URIs

### ISSUE THREAD

**Issue by AlBundy33** [castwide/solargraph#521]
After upgrading eclipse from 2021-09 to 2021-12 the solargraph-plugin is currently not workling.
@PyvesB analyzed the problem and found out that lsp4e sends faulty URIs to solargraph.

This is already reported to the lsp4e-project: https://github.com/eclipse/lsp4e/issues/29

But because java seems to be tolerant about the format
```
    URI _uri = new URI("file:///Z:/dev_tools/");
    System.out.println(_uri + ": " + new File(_uri).exists());
    _uri = new URI("file:/Z:/dev_tools/");
    System.out.println(_uri + ": " + new File(_uri).exists());
```
outputs
```
file:///Z:/dev_tools/: true
file:/Z:/dev_tools/: true
```
You maybe can also make uri_helpers.rb more tolerant by changing
https://github.com/castwide/solargraph/blob/949fa3c3be83de437f84c6acf8b9503347083471/lib/solargraph/language_server/uri_helpers.rb#L17
from
```
      def uri_to_file uri
        decode(uri).sub(/^file\:\/\//, '').sub(/^\/([a-z]\:)/i, '\1')
      end
```
to
```
      def uri_to_file uri
        decode(uri).sub(/^file\:\/\//, '').sub(/^file\:/, '').sub(/^\/([a-z]\:)/i, '\1')
      end
```
This ensures only that the leading `file:` is always removed.
At least in my case solargraph+eclipse+lsp4e is now working again with this change.

I've created this additional issue because I'm not sure when lsp4e fixes the issue and added it to a new release.

It's ok, if you don't want to change uri_to_file - in this case at least the workaround is documented here. :-)

**Comment by PyvesB** [comment]
Just to clarify the wording here: I don't think the URIs are _faulty_. My understanding is that having a single slashed `file:/` prefix is allowed by RFC 3986, it's simply not a commonly used form.

**Comment by AlBundy33** [comment]
I've manually patched uri_helpers.rb with your change and it seems to be working.
Do you have any idea when a new version will be available for gem install solargraph?

**Comment by AlBundy33** [comment]
Yesterday I thought about the defference between your and my change and the produce different results.
First I've checked what java says to one, two or three slashes after file:
```
    URI _uri;
    _uri = new URI("file:/Z:/dev_tools/");
    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
    // URI has an authority component
//    _uri = new URI("file://Z:/dev_tools/");
//    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
    _uri = new URI("file:///Z:/dev_tools/");
    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
    _uri = new URI("file:/dev_tools/");
    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
    // URI has an authority component
//    _uri = new URI("file://dev_tools/");
//    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
    _uri = new URI("file:///dev_tools/");
    System.out.println(_uri + "\t" + new File(_uri) + ": " + new File(_uri).exists());
```
```
file:/Z:/dev_tools/	Z:\dev_tools: true
file:///Z:/dev_tools/	Z:\dev_tools: true
file:/dev_tools/	\dev_tools: true
file:///dev_tools/	\dev_tools: true
```
Linux created the same results
```
file:/Z:/dev_tools/     /Z:/dev_tools: false
file:///Z:/dev_tools/   /Z:/dev_tools: false
file:/dev_tools/        /dev_tools: false
file:///dev_tools/      /dev_tools: false
```
-> output is false because I don't have this folder on the server where I've executed the class. ;-)

two slashes end up in an IllegalArgumentException: URI has an authority component so I've ignored this.

After that I've started `irb -r "%CD%\uri_helpers.rb"` with your change and called uri_to_file for the same paths as above
```
irb(main):001:0> ['file:/Z:/dev_tools/', 'file:///Z:/dev_tools/', 'file:/dev_tools/', 'file:///dev_tools/'].each { |p| puts Solargraph::LanguageServer::UriHelpers::uri_to_file(p) }
Z:/dev_tools/
Z:/dev_tools/
dev_tools/
/dev_tools/
```

After that I've changed uri_to_file from
```
decode(uri).sub(/^file\:\/\/?/, '').sub(/^\/([a-z]\:)/i, '\1')
```
to
```
        decode(uri)
          .sub(/^file\:\/\//, '')
          .sub(/^file\:/, '')
          .sub(/^\/([a-z]\:)/i, '\1')
```
and called the method in a new irb-session again
```
irb(main):001:0> ['file:/Z:/dev_tools/', 'file:///Z:/dev_tools/', 'file:/dev_tools/', 'file:///dev_tools/'].each { |p| puts Solargraph::LanguageServer::UriHelpers::uri_to_file(p) }
Z:/dev_tools/
Z:/dev_tools/
/dev_tools/
/dev_tools/
```
as you can see in my change the slash in file:/dev_tools/ is preserved.

**Comment by PyvesB** [comment]
Ah yes, good point, thanks for looking into this more closely. 🙏🏻  I we wanted to keep the single substitution, `/^file\:(?:\/\/)?/` should do the trick. I've updated the PR and also added a bunch of tests based on your example.

**Comment by AlBundy33** [comment]
I did a new test

```
  public static void main(String[] args)
    throws Exception
  {
    for (final String _s : new String[] {
        "file:/Z:/dev_tools/",
        //"file://Z:/dev_tools/", // URI has an authority component
        "file:///Z:/dev_tools/",
        "file:////Z:/dev_tools/",
        "file://///Z:/dev_tools/",
        "file://////Z:/dev_tools/",
        "file:///////Z:/dev_tools/",
        "file:/dev_tools/",
        // "file://dev_tools/", // URI has an authority component
        "file:///dev_tools/",
        "file:////dev_tools/",
        "file://///dev_tools/",
        "file:///////dev_tools/",
    })
    {
      final URI _uri = new URI(_s);
      System.out.println(_uri + "\t" + new File(_uri));
    }
  }
```

output on windows
```
file:/Z:/dev_tools/	Z:\dev_tools
file:///Z:/dev_tools/	Z:\dev_tools
file:////Z:/dev_tools/	Z:\dev_tools
file://///Z:/dev_tools/	Z:\dev_tools
file://////Z:/dev_tools/	Z:\dev_tools
file:///////Z:/dev_tools/	Z:\dev_tools
file:/dev_tools/	\dev_tools
file:///dev_tools/	\dev_tools
file:////dev_tools/	\\dev_tools
file://///dev_tools/	\\dev_tools
file:///////dev_tools/	\\dev_tools
```
output on linux
```
file:/Z:/dev_tools/     /Z:/dev_tools
file:///Z:/dev_tools/   /Z:/dev_tools
file:////Z:/dev_tools/  /Z:/dev_tools
file://///Z:/dev_tools/ /Z:/dev_tools
file://////Z:/dev_tools/        /Z:/dev_tools
file:///////Z:/dev_tools/       /Z:/dev_tools
file:/dev_tools/        /dev_tools
file:///dev_tools/      /dev_tools
file:////dev_tools/     /dev_tools
file://///dev_tools/    /dev_tools
file:///////dev_tools/  /dev_tools
```

```
[
	"file:/Z:/dev_tools/",
	# "file://Z:/dev_tools/", // URI has an authority component
	"file:///Z:/dev_tools/",
	"file:////Z:/dev_tools/",
	"file://///Z:/dev_tools/",
	"file://////Z:/dev_tools/",
	"file:///////Z:/dev_tools/",
	"file:/dev_tools/",
	# "file://dev_tools/", // URI has an authority component
	"file:///dev_tools/",
	"file:////dev_tools/",
	"file://///dev_tools/",
	"file:///////dev_tools/",
].each { |uri| puts CGI.unescape(uri).sub(/^file\:(?:\/\/)?/, '').sub(/^\/([a-z]\:)/i, '\1') }
```
output
```
Z:/dev_tools/
Z:/dev_tools/
//Z:/dev_tools/
///Z:/dev_tools/
////Z:/dev_tools/
/////Z:/dev_tools/
/dev_tools/
/dev_tools/
//dev_tools/
///dev_tools/
/////dev_tools/
```

So 'ive tried
```
decode(uri).sub(/^file\:\/\//, '').sub(/^file\:/, '').sub(/^\/+([a-z]\:)/i, '\1')
```
multiple replacements:
first: replace file:// (the default)
second: remove still existing file:
thrid: replace all leading / if they are followed by a letter and :

```
[
	"file:/Z:/dev_tools/",
	# "file://Z:/dev_tools/", // URI has an authority component
	"file:///Z:/dev_tools/",
	"file:////Z:/dev_tools/",
	"file://///Z:/dev_tools/",
	"file://////Z:/dev_tools/",
	"file:///////Z:/dev_tools/",
	"file:/dev_tools/",
	# "file://dev_tools/", // URI has an authority component
	"file:///dev_tools/",
	"file:////dev_tools/",
	"file://///dev_tools/",
	"file:///////dev_tools/"
].each { |uri| puts uri + "\t" + CGI.unescape(uri).sub(/^file\:\/\//, '').sub(/^file\:/, '').sub(/^\/+([a-z]\:)/i, '\1') }
```
output
```
file:/Z:/dev_tools/     Z:/dev_tools/
file:///Z:/dev_tools/   Z:/dev_tools/
file:////Z:/dev_tools/  Z:/dev_tools/
file://///Z:/dev_tools/ Z:/dev_tools/
file://////Z:/dev_tools/        Z:/dev_tools/
file:///////Z:/dev_tools/       Z:/dev_tools/
file:/dev_tools/        /dev_tools/
file:///dev_tools/      /dev_tools/
file:////dev_tools/     //dev_tools/
file://///dev_tools/    ///dev_tools/
file:///////dev_tools/  /////dev_tools/
```
for windows-path we get always the part with the drive-letter, and on linux we may have a lot / but this souldn't be an issue.

There might be an issue with unc-paths.
Java translates `\\foo\bar\test.txt` to `file:////foo/bar/test.txt`
and `new File(new URI("file:////foo/bar/test.txt"))` translates it back to `\\foo\bar\test.txt`
where the above replacement translates it to `//foo/bar/test.txt`

**Comment by PyvesB** [comment]
Are there actually any language server clients that produce URIs with more than one leading slash? I think we shoul avoid scope creep and stick to the issue that we know happens with one of them, i.e. `file:` prefix without the common `//` part. Trying to solve other hypothetical problems that won't happen in practice will do little good in terms of code complexity and performance. :)

**Comment by AlBundy33** [comment]
No - I haven't seen a language server with this kind of URLs but I try to be as much devensive as possible. 🙂
With only file:/ and file:// the output of
```
[
	"file:/Z:/dev_tools/",
	# "file://Z:/dev_tools/", // URI has an authority component
	"file:///Z:/dev_tools/",
	"file:/dev_tools/",
	# "file://dev_tools/", // URI has an authority component
	"file:///dev_tools/",
].each { |uri| puts CGI.unescape(uri).sub(/^file\:(?:\/\/)?/, '').sub(/^\/([a-z]\:)/i, '\1') }
```
looks like this
```
Z:/dev_tools/
Z:/dev_tools/
/dev_tools/
/dev_tools/
```

So I think this is enough to fix the issue 🙂
