### ISSUE TITLE
Request textDocument/hover failed.   Message: [SystemStackError] stack level too deep   Code: -32603 

### ISSUE THREAD

**Issue by LeonineKing1199** [castwide/solargraph#96]
I continuously get these errors using Solargraph. I can provide more info if needed (sorry if vague).

**Comment by castwide** [comment]
Which version of the gem are you using? This sounds related to #83, which has been fixed since version 0.26.0 (current is 0.28.2).

**Comment by LeonineKing1199** [comment]
Hmm, I'm using the latest (0.28.2) and I still get it.

I was wondering if it was the code quality that's causing it :P

I am working on quite the legacy project. I'm not sure what info is helpful or not but I can try and reproduce the issue in isolation.

**Comment by castwide** [comment]
In all likelihood, it happens when you hover the mouse over some piece of code. If you could identify it, that would be very helpful.

If you're using VS Code, there might also be additional information in the developer console (Help -> Toggle Developer Tools).

**Comment by castwide** [comment]
I managed to reproduce the error by hovering over `quz` in the following code:

```Ruby
@foo = @bar
@bar = @foo.quz
```

When Solargraph tries to define `quz`, first it tries to infer a type for `@foo`. Then it tries to infer `@bar`, which tries to infer `@foo`, which tries to infer `@bar` ad infinitum. It's basically the #83 bug with an additional layer of abstraction.

We'll need to change type inference so it doesn't recurse back into previous variable assignments.

**Comment by castwide** [comment]
Fixed in gem v0.28.3.
